title: 黒メモ

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      permalink: /:year/:month/:title:output_ext
     
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  
paginate: 20
paginate_path: "page:num"

author : kuro  

timezone: Asia/Tokyo

#未来日付の公開有無
future: ture
