
title: 黒メモ
show_downloads: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      permalink: /:year/:month/:title:output_ext
     
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  
paginate: 2
paginate_path: "page:num"
